# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       gemini-kernel

# >> macros
# << macros

Summary:    Kernel build package
Version:    1.0
Release:    1
Group:      System
License:    GPLv2
Source0:    %{name}.tar.gz
Source100:  gemini-kernel.yaml

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
# << files
